##BSREAD USING EVR
## Macros: 
##
## - STORE_EVENT 
##
## Optional parameters/macros [default]
##  - SYS [$(IOC)] 
##  - BSREAD_PORT [9999]
##  - BSREAD_MODE [PUSH]
##  - EVR [EVR0]
##  - BSREAD_PULSEID [$(SYS=$(IOC))-$(EVR):RX-PULSEID]
##  - BSREAD_TS_SEC  [$(SYS=$(IOC))-$(EVR):RX-MTS-SEC]
##  - BSREAD_TS_NSEC [$(SYS=$(IOC))-$(EVR):RX-MTS-NSEC]
##  - READ_FLNK []
##  - STORE_FLNK []
##  - PULSEID_OFFSET [0]
##  - EVENT_NAME [$(EVENT_NAME=bsread$(BSREAD_PORT=9999))]

require bsread


PREFIX="$(SYS=$(IOC))-BSREAD$(BSREAD_PORT=9999)"
EVR_PFX="$(SYS=$(IOC))-$(EVR=EVR0)"

dbLoadRecords "bsread_storesend.template", "P=$(PREFIX),EVR=$(EVR=EVR0),STORE_EVENT=$(STORE_EVENT),EVENT_NAME=$(EVENT_NAME=bsread$(BSREAD_PORT=9999)),BSREAD_PULSEID=$(BSREAD_PULSEID=$(EVR_PFX):RX-PULSEID),BSREAD_TS_SEC=$(BSREAD_TS_SEC=$(EVR_PFX):RX-MTS-SEC),BSREAD_TS_NSEC=$(BSREAD_TS_NSEC=$(EVR_PFX):RX-MTS-NSEC),FLNK=$(STORE_FLNK=)"
dbLoadRecords "bsread.template", "P=$(PREFIX),BSREAD_PORT=$(BSREAD_PORT=9999),EVENT_NAME=$(EVENT_NAME=bsread$(BSREAD_PORT=9999)),PULSEID_OFFSET=$(PULSEID_OFFSET=0),BSREAD_PULSEID=$(PREFIX):STORED-PULSE,BSREAD_TS_SEC=$(PREFIX):STORED-TS-SEC,BSREAD_TS_NSEC=$(PREFIX):STORED-TS-NSEC"

bsreadConfigure($(BSREAD_PORT=9999),$(BSREAD_PORT=9999),$(BSREAD_MODE=PUSH),$(HWM=10))
