# $Header: /cvs/G/CRLOGIC/src/CRLOGICVME58E/Makefile,v 1.1 2012/02/22 07:57:09 ebner Exp $

include /ioc/tools/driver.makefile
EXCLUDE_VERSIONS = 3.13
USR_CFLAGS += -O0
PROJECT = CRLOGICVME58E
LIBVERSION=4.4.4
