# $Header: /cvs/G/CRLOGIC/src/CRLOGICHy8001Trigger/Makefile,v 1.1 2011/10/18 07:03:28 ebner Exp $

include /ioc/tools/driver.makefile
EXCLUDE_VERSIONS = 3.13
USR_CFLAGS += -O0
PROJECT = CRLOGICHy8001Trigger