# $Header: /cvs/G/CRLOGIC/src/CRLOGICChannel/Makefile,v 1.1 2011/10/18 07:03:27 ebner Exp $

include /ioc/tools/driver.makefile
EXCLUDE_VERSIONS = 3.13
USR_CFLAGS += -O0
PROJECT = CRLOGICChannel
LIBVERSION=4.4.4