# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bunchData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bunchData.proto',
  package='bsdaqPB',
  serialized_pb='\n\x0f\x62unchData.proto\x12\x07\x62sdaqPB\"\x8f\x01\n\tBunchData\x12\x10\n\x08pulse_id\x18\x01 \x02(\x04\x12)\n\x06record\x18\x02 \x03(\x0b\x32\x19.bsdaqPB.BunchData.Record\x1a\x45\n\x06Record\x12\x13\n\x0brecord_name\x18\x01 \x02(\t\x12\x12\n\ndouble_val\x18\x02 \x03(\x01\x12\x12\n\nstring_val\x18\x03 \x03(\t')




_BUNCHDATA_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='bsdaqPB.BunchData.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_name', full_name='bsdaqPB.BunchData.Record.record_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_val', full_name='bsdaqPB.BunchData.Record.double_val', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_val', full_name='bsdaqPB.BunchData.Record.string_val', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=172,
)

_BUNCHDATA = _descriptor.Descriptor(
  name='BunchData',
  full_name='bsdaqPB.BunchData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pulse_id', full_name='bsdaqPB.BunchData.pulse_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record', full_name='bsdaqPB.BunchData.record', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BUNCHDATA_RECORD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=172,
)

_BUNCHDATA_RECORD.containing_type = _BUNCHDATA;
_BUNCHDATA.fields_by_name['record'].message_type = _BUNCHDATA_RECORD
DESCRIPTOR.message_types_by_name['BunchData'] = _BUNCHDATA

class BunchData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Record(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BUNCHDATA_RECORD

    # @@protoc_insertion_point(class_scope:bsdaqPB.BunchData.Record)
  DESCRIPTOR = _BUNCHDATA

  # @@protoc_insertion_point(class_scope:bsdaqPB.BunchData)


# @@protoc_insertion_point(module_scope)
